const cars = [
    {
      car: "Koenigsegg Jesko",
      carType: "Sport",
      carImage: "https://example.com/car1.jpg",
      carGasoline: "100",
      carManuals: "Manual",
      carPeople: "2",
      carPrice: "99.00",
    },
    {
      car: "Nissan GT-R Nismo",
      carType: "Sport",
      carImage: "https://example.com/car2.jpg",
      carGasoline: "80",
      carManuals: "Automatic",
      carPeople: "2",
      carPrice: "80.00",
 
    },
    {
      car: "Rolls-Royce Phantom",
      carType: "Sedan",
      carImage: "https://example.com/car3.jpg",
      carGasoline: "70",
      carManuals: "Automatic",
      carPeople: "4",
      carPrice: "96.00",
    },
    {
      car: "Lamborghini Aventador",
      carType: "Sport",
      carImage: "https://example.com/car4.jpg",
      carGasoline: "90",
      carManuals: "Manual",
      carPeople: "2",
      carPrice: "120.00",
    },
    {
      car: "BMW M3",
      carType: "Coupe",
      carImage: "https://example.com/car5.jpg",
      carGasoline: "75",
      carManuals: "Manual",
      carPeople: "4",
      carPrice: "85.00",
    },
    {
      car: "Mercedes-Benz S-Class",
      carType: "Sedan",
      carImage: "https://example.com/car6.jpg",
      carGasoline: "65",
      carManuals: "Automatic",
      carPeople: "5",
      carPrice: "110.00",
    },
    {
      car: "Ferrari LaFerrari",
      carType: "Sport",
      carImage: "https://example.com/car7.jpg",
      carGasoline: "95",
      carManuals: "Manual",
      carPeople: "2",
      carPrice: "130.00",
    },
    {
      car: "Audi R8",
      carType: "Sport",
      carImage: "https://example.com/car8.jpg",
      carGasoline: "85",
      carManuals: "Automatic",
      carPeople: "2",
      carPrice: "90.00",
    },
    {
      car: "Tesla Model S",
      carType: "Sedan",
      carImage: "https://example.com/car9.jpg",
      carGasoline: "Electric",
      carManuals: "Automatic",
      carPeople: "5",
      carPrice: "95.00",
    },
    {
      car: "Porsche 911 Turbo",
      carType: "Sport",
      carImage: "https://example.com/car10.jpg",
      carGasoline: "88",
      carManuals: "Manual",
      carPeople: "2",
      carPrice: "115.00",
    },
  ];

  export default cars